import CitationCard from "./CitationCard";

const ResearchExperience = () => {
  return (
    <div className="pb-10">
      <h2 className="text-2xl font-bold mb-4">Publications</h2>
      <div className="mb-4 text-[#333333]">
        {/* <h3 className="pb-2">
          Currently researching AI safety and reliability in the classroom. My goal is to democratize education for learners of all backgrounds. My work has led to 10 conference publications:&nbsp;
          <a
            href="https://scholar.google.com/citations?user=t9TUznoAAAAJ&hl=en"
            className="text-[#d32f2f] underline"
            target="_blank"
            rel="noopener noreferrer"
          >
            Google Scholar.
          </a>
        </h3> */}
      </div>

      {/* Publication Cards */}
      <div className="mt-0 text-[#333333]">
        <CitationCard
            title="Global PIQA: Evaluating Physical Commonsense Reasoning Across 100+ Languages and Cultures"
            authors="Tyler A Chang, Catherine Arnett, Authors at the 5th Multilingual Representation Learning (MRL) Workshop"
            venue="SIGTYP"
            year={2025}
            link="https://arxiv.org/pdf/2510.24081"
            highlightName="Andrew Tran"
        />

        <CitationCard
          title="Hacking Student Leadership: Peer Mentorship and Leadership Skill Development Among Hackathon Organizers"
          authors="Kush Patel, Andrew Tran, Christine Kapp, Daniel Bicalho, Yatri Patel, Chiku Okechukwu, Egi Rama, Stephen MacNeil"
          venue="SIGCSETS"
          year={2025}
          link="https://dl.acm.org/doi/10.1145/3641555.3705193"
          highlightName="Andrew Tran"
        />

        <CitationCard
          title="Decoding logic errors: a comparative study on bug detection by students and large language models"
          authors="Stephen MacNeil, Paul Denny, Andrew Tran, Juho Leinonen, Seth Bernstein, Arto Hellas, Sami Sarsa, Joanne Kim"
          venue="ACE"
          year={2024}
          link="https://arxiv.org/abs/2311.16017"
          highlightName="Andrew Tran"
        />

        <CitationCard
          title="Generating multiple choice questions for computing courses using large language models"
          authors="Andrew Tran, Kenneth Angelikas, Egi Rama, Chiku Okechukwu, David H Smith, Stephen MacNeil"
          venue="FIE"
          year={2023}
          link="https://ieeexplore.ieee.org/document/10342898"
          highlightName="Andrew Tran"
        />

        <CitationCard
          title="Using large language models to automatically identify programming concepts in code snippets"
          authors="Andrew Tran, Linxuan Li, Egi Rama, Kenneth Angelikas, Stephen MacNeil"
          venue="ICER"
          year={2023}
          link="https://dl.acm.org/doi/10.1145/3568812.3603482"
          highlightName="Andrew Tran"
        />

        <CitationCard
          title="Prompt middleware: Mapping prompts for large language models to UI affordances"
          authors="Stephen MacNeil, Andrew Tran, Joanne Kim, Ziheng Huang, Seth Bernstein, Dan Mogil"
          venue=""
          year={2023}
          link="https://arxiv.org/pdf/2307.01142"
          highlightName="Andrew Tran"
        />

        <CitationCard
          title="Comparing code explanations created by students and large language models"
          authors="Juho Leinonen, Paul Denny, Stephen MacNeil, Sami Sarsa, Seth Bernstein, Joanne Kim, Andrew Tran, Arto Hellas"
          venue="ITICSE"
          year={2023}
          link="https://dl.acm.org/doi/pdf/10.1145/3587102.3588785"
          highlightName="Andrew Tran"
        />

        <CitationCard
          title="Experiences from using code explanations generated by large language models in a web software development e-book"
          authors="Stephen MacNeil, Andrew Tran, Arto Hellas, Joanne Kim, Sami Sarsa, Paul Denny, Seth Bernstein, Juho Leinonen"
          venue="SICGSETS"
          year={2023}
          link="https://arxiv.org/abs/2211.02265"
          highlightName="Andrew Tran"
        />

        <CitationCard
          title="The Implications of Large Language Models for CS Teachers and Students"
          authors="Stephen MacNeil, Joanne Kim, Juho Leinonen, Paul Denny, Seth Bernstein, Brett A Becker, Michel Wermelinger, Arto Hellas, Andrew Tran, Sami Sarsa, James Prather, Viraj Kumar"
          venue="SIGCSETS"
          year={2023}
          link="https://www.researchgate.net/profile/Stephen-Macneil/publication/366412208_The_Implications_of_Large_Language_Models_for_CS_Teachers_and_Students/links/63a0ce1c40358f78eb018df7/The-Implications-of-Large-Language-Models-for-CS-Teachers-and-Students.pdf"
          highlightName="Andrew Tran"
        />

        <CitationCard
          title="Automatically generating CS learning materials with large language models"
          authors="Stephen MacNeil, Andrew Tran, Juho Leinonen, Paul Denny, Joanne Kim, Arto Hellas, Seth Bernstein, Sami Sarsa"
          venue="SICGSETS"
          year={2023}
          link="https://arxiv.org/pdf/2212.05113"
          highlightName="Andrew Tran"
        />

        <CitationCard
          title="Generating diverse code explanations using the gpt-3 large language model"
          authors="Stephen MacNeil, Andrew Tran, Dan Mogil, Seth Bernstein, Erin Ross, Ziheng Huang"
          venue="ICER"
          year={2022}
          link="https://par.nsf.gov/servlets/purl/10397860"
          highlightName="Andrew Tran"
        />
      </div>

      {/* Research Experience
      <div className="text-[#f9f9f9] pt-6">
        <div>
          <h3 className="font-semibold">Undergraduate Researcher, Generative AI</h3>
          <p className="text-sm">Temple HCI Lab - Philadelphia, PA</p>
          <p className="text-sm">January 2022 - Present</p>
        </div>

        <div className="pt-4 text-white">
          <h3 className="font-semibold">Undergraduate Researcher, Generative AI</h3>
          <p className="text-sm">National Science Foundation (NSF) - Philadelphia, PA </p>
          <p className="text-sm">May 2022 - August 2022</p>
        </div>
      </div> */}
    </div>
  );
};

export default ResearchExperience;
